INSERT INTO stationgame.products (name,image,creation_date,modified_date,deletion_date,price,description,category_id,brand_id) VALUES
	 ('Madden NFL 22','1639948377757.jpg','2021-12-19 21:12:57',NULL,NULL,9789,'Madden NFL 22 es donde se juega el partido. Es todo lo que amas de la NFL inyectado en cada modo mediante el nuevo d�a del partido din�mico. Tra�do a la vida por la IA de estrellas con estad�sticas de nueva generaci�n (Next Gen Stats Star-Driven AI) y elementos de atm�sfera del d�a de juego (Gameday Atmosphere), el d�a de juego din�mico (Dynamic Gameday) ofrece la experiencia de juego m�s inteligente hasta el momento, todo impulsado con datos de la vida real. Dynamic Gameday, Next Gen Stats Star-Driven AI y Gameday Atmosphere son exclusivos de las versiones PlayStation 5 y Xbox Series X|S de Madden NFL 22. **Oferta promocional de preventa de Madden NFL 22 - Esta oferta promocional de preventa caduca el 20 de agosto de 2021. Canjea la oferta antes del 1 de septiembre de 2022 para recibir 20 puntos de personal para el modo Franchise cl�sico, conectado para un jugador ("Puntos de personal"), 1 c�psula Vanity de atleta de portada, 1 art�culo de un jugador estrella de la NFL Elite y el desbloqueo de 10 niveles en la clase de jugador "General" para el avatar del jugador en Face of the Franchise y The Yard.',2,1),
	 ('Ghost of Tsushima','1639948441833.jpg','2021-12-19 21:14:01',NULL,NULL,11989,'A finales del siglo XII, el Imperio Mongol ha puesto residuos a todas las naciones a lo largo de su campa�a para conquistar el Oriente. La isla Tsushima es todo lo que se encuentra entre Jap�n continental y una enorme flota de invasi�n mongol dirigida por el general despiadado y astutuoso, Khotun Khan. A medida que la isla se quema en la caminata de la primera ola del asalto Mongol, el valiente guerrero samur�i Jin Sakai se mantiene resuelto. Como uno de los �ltimos miembros supervivientes de su clan, Jin est� decidido a hacer lo que necesite, a cualquier costo, para proteger a su pueblo y recuperar su hogar. Debe dejar de lado las tradiciones que lo han formado como guerrero para forjar un nuevo camino, el camino del fantasma, y salvar una guerra no convencional por la libertad de Tsushima. Ghost of Tsushima DIRECTOR''S CUT incluye: juego completo. - Expansi�n Iki Island: nueva historia, mini-juegos, tipos enemigos y m�s. - Modo cooperativo en l�nea Legends. - Mini libro de arte digital de Dark Horse. - Comentario del director: el equipo creativo se asienta con un famoso historiador japon�s para mirar el mundo de Ghost of Tsushima y c�mo se compara con los eventos de la vida real que lo inspir�. - Un punto t�cnico. - Dije del recuerdo de Hachiman. - Juego de piel de h�roe de Tsushima: m�scara dorada, kit de espada, caballo, sill�n.',2,1),
	 ('Jurassic World Evolution ','1639948502569.jpg','2021-12-19 21:15:02',NULL,NULL,7895,'Jurassic World Evolution 2 es la secuela tan esperada de la exitosa evoluci�n Jurassic World Evolution, bas�ndose en la innovadora e inmersiva simulaci�n de gesti�n de 2018. Introduce una campa�a atractiva, nueva y narrativa, nuevas caracter�sticas incre�bles y nuevos dinosaurios sorprendentes que cobran vida con una autenticidad cautivadora. Junto con una construcci�n ampliada y m�s opciones de personalizaci�n, el resultado es un juego a�n m�s grande, mejor y aut�ntico de Jurassic World.',2,3),
	 ('NASCAR HEAT Ultimate Edition+','1639948566643.jpg','2021-12-19 21:16:06',NULL,NULL,12789,'NASCAR Heat Ultimate Edition+, el videojuego oficial de la temporada 2020, la serie de carreras de stockcar m�s popular del mundo te pone al volante y te desaf�a a convertirte en el campe�n de la serie NASCAR Cup Series. Cuenta con los equipos oficiales de 2020, pilotos, coches y horarios de las tres NASCAR National Series, as� como el Xtreme Dirt Tour, compitiendo en 39 pistas aut�nticas. Ultimate Edition+ incluye todo en NASCAR Heat 5 Ultimate Edition, adem�s de la NASCAR Cup Series Roster 2021 y esquemas de pintura primaria 2021. El contenido destacado incluye esquemas de pintura Throwback y Playoff 2020, Tony Stewart como personaje jugable, �y m�s!',2,2),
	 ('Halo Infinite','1639948615531.jpg','2021-12-19 21:16:55',NULL,NULL,6367,'Cuando toda la esperanza se pierde y el destino de la humanidad cuelga en el equilibrio, el jefe maestro est� listo para enfrentarse al enemigo m�s despiadado que jam�s haya enfrentado. La legendaria serie Halo regresa con la historia m�s amplia de Master Chief hasta el momento.',2,3),
	 ('Ratchet & Clank: Rift Apart','1639948660644.jpg','2021-12-19 21:17:40',NULL,NULL,12474,'Los aventureros intergal�cticos han vuelto con un flequillo. Ay�dales a detener una intenci�n rob�tica de conquistar mundos transdimensionales, con su propio universo junto en la l�nea de disparo. Voltea tu camino a casa con un arsenal de armas escandalosas. Experimenta el Shuffle de Rifts dimensional y el juego din�mico. Explora planetas nunca antes vistas y versiones de dimensiones alternativas de viejos favoritos. Caracter�sticas de PS5: siente acciones en el juego a trav�s de la retroalimentaci�n h�ptica del controlador inal�mbrico de doble sentido. Toma el control total de la mec�nica avanzada de armas, hecho posible mediante gatillos adaptativos. Planet-hop a hipervelocidad a trav�s de la carga casi instant�nea del SSD de la consola PS5. Sumerge tus o�dos con Tempest 3D Audio Tech mientras trabajas para salvar el universo. La iluminaci�n y el seguimiento de los rayos mejorados representan deslumbrantes mundos en el juego, mostrados en 4K y HDR n�tidos, din�micos. Elige el modo de rendimiento para disfrutar de 60 fotogramas por segundo de juego. (Con auriculares compatibles). Dynamic 4K y HDR requieren un televisor o pantalla compatible con 4K y HDR.',2,1),
	 ('Disney Classic Games Collection','1639948714943.jpg','2021-12-19 21:18:34',NULL,NULL,11254,'The Expanded Collection: Juega a trav�s de m�ltiples versiones diferentes de los queridos juegos de Aladdin, The Lion King y The Jungle Book que se han creado a lo largo de los a�os, incluyendo tanto versiones de consola como de mano.',2,2),
	 ('Animal Crossing: New Horizons','1639948778749.jpg','2021-12-19 21:19:38',NULL,NULL,14583,'Esc�pate a una isla desierta y crea tu propio para�so mientras exploras, creas y personalizas en el juego Animal Crossing: New Horizons. Su escapada a la isla tiene una gran cantidad de recursos naturales que se pueden utilizar para crear todo, desde herramientas hasta comodidades de criatura. Puede cazar insectos en la grieta del amanecer, decorar su para�so durante todo el d�a, o disfrutar de la puesta de sol en la playa mientras pesca en el oc�ano. La hora del d�a y la temporada coinciden con la vida real, por lo que cada d�a en su isla es una oportunidad para registrarse y encontrar nuevas sorpresas durante todo el a�o.

Muestre su utop�a de la isla a familiares y amigos, o empacar sus maletas y visite las suyas. Ya sea jugar en l�nea o con otros a su lado, la vida en la isla es a�n mejor cuando se puede compartirlo. Incluso sin saltar en un vuelo, conocer�s a un elenco de encantadores residentes de animales repletos de personalidad. Caras amigables como Tom Nook e Isabelle prestar�n sus servicios y felizmente le ayudar�n a hacer crecer su comunidad en ciernes. Esc�pate a tu escapada en la isla, sin embargo, cuando quieras y donde quieras. ',2,2),
	 ('Back 4 Blood','1639948834759.jpg','2021-12-19 21:20:34',NULL,NULL,5735,'Back 4 Blood es un emocionante tirador cooperativo en primera persona de los creadores de la aclamada franquicia dejada 4 muertos. Est�s en el centro de una guerra contra los montados. Estos anfitriones de un par�sito mortal se han convertido en criaturas aterradoras dobladas en devorar lo que queda de la civilizaci�n. Con la extinci�n de la humanidad en la l�nea, depende de ti y de tus amigos llevar la lucha al enemigo, erradicar a los montados y recuperar el mundo.',2,3),
	 ('Battlefield 2042','1639948874522.jpg','2021-12-19 21:21:14',NULL,NULL,8795,'Battlefield 2042 es un tirador en primera persona que marca el regreso a la ic�nica guerra completa de la franquicia. En un mundo casi futuro transformado por el trastorno se adapta y supera los campos de batalla que cambian din�micamente con la ayuda de tu escuadr�n y un arsenal de vanguardia. Con soporte para 128 jugadores en PlayStation 5, Battlefield 2042 trae una escala sin precedentes en grandes terrenos de batalla en todo el mundo. Los jugadores asumir�n varias experiencias masivas, desde modos multijugador actualizados como Conquest y Breakthrough hasta la nueva zona de peligro. *Condiciones y restricciones. Ning�n fabricante de armas, veh�culos o engranajes est� afiliado o ha respaldado este juego.',2,1);
INSERT INTO stationgame.products (name,image,creation_date,modified_date,deletion_date,price,description,category_id,brand_id) VALUES
	 ('Kena: Bridge of Spirits','1639948910210.jpg','2021-12-19 21:21:50',NULL,NULL,12678,'Una aventura de acci�n basada en historias que combina la exploraci�n con el combate acelerado. Mientras Kena, los jugadores encuentran y crecen un equipo de compa�eros espirituales encantadores llamados Rot, mejorando sus habilidades y creando nuevas formas de manipular el medio ambiente. Kena, un joven gu�a espiritual, viaja a un pueblo abandonado en busca del sagrado santuario de monta�a. Ella lucha por descubrir los secretos de esta comunidad olvidada escondida en un bosque cubierto donde los esp�ritus errantes est�n atrapados. Kena: Bridge of Spirits - Deluxe Edition incluye: juego base, banda sonora digital oficial, personal de Kena �nico, piel de putrefacci�n dorada, hoja de pegatinas exclusivas para minoristas, sombreros de celebraci�n �nicos para la putrefacci�n.',2,1),
	 ('Minecraft Dungeons Hero Edition','1639948951403.jpg','2021-12-19 21:22:31',NULL,NULL,7689,'Lucha a trav�s de un nuevo juego de acci�n y aventura, inspirado en los cl�sicos orugas de calabozos y en el universo de Minecraft. �Viste a los calabozos solos o �nete con amigos! Hasta cuatro jugadores pueden luchar juntos a trav�s de niveles llenos de acci�n, llenos de tesoros y variados, todo en una b�squeda �pica para salvar a los aldeanos y derrotar al malvado Arch-Illager. Descubre un mont�n de poderosas nuevas armas y art�culos que te ayudar�n a derrotar enjambres despiadados de turbas nuevas y desagradables. �Lucha o huye a trav�s de ca�ones, pantanos y, por supuesto, las minas! Cualquier aventurero valiente o tonto suficiente para explorar este mundo bloqueado y hermoso tendr� que prepararse. �Tan r�pidamente! Minecraft Dungeons Hero Edition incluye el contenido de Hero Pass DLC: una capa de h�roe, dos pieles de jugadores y una mascota de pollo. Tambi�n incluye los paquetes DLC de Jungle Awakens y Creeping Winters.',2,3),
	 ('Mortal Kombat 11 Ultimate','1639949001074.jpg','2021-12-19 21:23:21',NULL,NULL,11590,'Preordena y obt�n el paquete de piel de los guerreros del tiempo con saibot de red oscura, HCF Liu Kang & blood Moon skarlet. La experiencia definitiva Mk11. Toma el control de los protectores de la tierra en las dos campa�as de historias aclamadas del juego mientras corren para evitar que Kronika rebobinar el tiempo y reiniciar la historia. Las amistades se prueban, y se forjan nuevas alianzas en la batalla para salvar toda la existencia. Mk11 Ultimate cuenta con la lista completa de 37 personajes, incluyendo nuevas adiciones Rain Mileena & Rambo. Mortal Kombat 11 muestra cada divertida amistad, mortal mortal y golpe mortal como nunca antes. Estar�s tan cerca de la lucha que puedes sentirlo. Incluye Mortal Kombat 11, Kombat Pack 1, expansi�n postmatem�ticas y Kombat Pack 2. Mk11 Ultimate est� habilitado para entrega inteligente e incluye actualizaciones gratuitas en la serie Xbox X: resoluci�n din�mica 4K, im�genes mejoradas, tiempos de carga significativamente mejorados y compatibilidad Cross-Platform/CrossGen.',2,3),
	 ('PlayStation 5','1639949080925.jpg','2021-12-19 21:24:40',NULL,NULL,210999,'La consola PS5 desata nuevas posibilidades de juego que nunca esperabas. Experimenta una carga r�pida con un SSD de alta velocidad, inmersi�n m�s profunda con soporte para retroalimentaci�n t�ctil, disparadores adaptativos y audio 3D, y una nueva generaci�n de incre�bles juegos de PlayStation.',1,1),
	 ('Xbox Series S','1639949133465.jpg','2021-12-19 21:25:33',NULL,NULL,89999,'Obt�n el paquete totalmente digital Xbox Series S � Fortnite & Rocket League con el Midnight Drive Pack, 1,000 V-Bucks, y 1,000 cr�ditos de Rocket League. Con el paquete Midnight Drive para Fortnite, puedes personalizar tu avatar con el traje Dark Skully, Dark Skully Satchel Back Bling, Dark Splitter Pickaxe, y 1,000 V-Bucks para pasar en art�culos favoritos en Fortnite Battle Royale y m�s. Para el contenido adicional de Rocket League, obtienes el destacado auto Masamune Purple Virtual Wave Boost, Purple Zefram Wheels y 1.000 Credits de Rocket League que se pueden utilizar para construir Blueprints, actualizar a Rocket Pass Premium, o comprar el contenido m�s deseado de la tienda de art�culos de Rocket League. Y, como Fortnite y Rocket League son libres para jugar con Xbox, puedes jugar directamente con tus amigos.',1,3),
	 ('Nintendo Switch OLED','1639949238614.jpg','2021-12-19 21:27:18',NULL,NULL,124999,'Presentamos al miembro m�s reciente de la familia Nintendo Switch.

Juega en casa en el televisor o en el camino con el sistema Nintendo Switch modelo OLED y su vibrante pantalla OLED de 7 pulgadas. Adem�s de una nueva pantalla con colores vivos y contraste n�tido, el modelo OLED Nintendo Switch incluye un amplio soporte ajustable para �ngulos de visi�n m�s c�modos, un dock con un puerto LAN con cable para modo TV (cable LAN se vende por separado), 64 GB de almacenamiento interno y audio mejorado en modos de mano y mesa utilizando los altavoces del sistema.',1,2),
	 ('Xbox Series X','1639949354560.jpg','2021-12-19 21:29:14','2021-12-19 21:30:22',NULL,213999,'Presentamos Xbox Series X, la Xbox m�s r�pida y potente que nunca. Juega miles de t�tulos de cuatro generaciones de consolas: todos los juegos se ven y juegan mejor en Xbox Series X. En el coraz�n de la Serie X se encuentra la arquitectura Xbox Velocity, que combina una SSD personalizada con software integrado para un juego m�s r�pido y optimizado con tiempos de carga significativamente reducidos. Mu�vete sin problemas entre varios juegos en un destello con un resumen r�pido. Explora nuevos mundos ricos y disfruta de la acci�n como nunca antes con los inigualables 12 Teraflops de potencia de procesamiento gr�fico crudo. Disfruta de juegos en 4K con hasta 120 fotogramas por segundo, sonido espacial 3D avanzado y mucho m�s. Empieza con una biblioteca instant�nea de m�s de 100 juegos de alta calidad, incluidos todos los nuevos t�tulos de Xbox Game Studios el d�a en que se lanzan como Halo Infinite, con Xbox Game Pass Ultimate (la membres�a se vende por separado).',1,3),
	 ('Gamepad Sony DualSense Midnight Black','1639949798989.jpg','2021-12-19 21:36:38',NULL,NULL,12999,'Enciende tus noches de juego en tu consola PS5 con el mando inal�mbrico DualSense Midnight Black. Parte de una nueva gama de colores tem�ticos de galaxia, este elegante dise�o se inspira en c�mo vemos las maravillas del espacio a trav�s del cielo nocturno, con tonos sutiles de detalles en negro y gris claro. Descubre una experiencia de juego m�s profunda y altamente envolvente** que da vida a la acci�n en las palmas de tus manos. El controlador inal�mbrico DualSense ofrece una respuesta t�ctil envolvente*, disparadores adaptativos din�micos* y un micr�fono integrado, todo integrado en un c�modo dise�o ic�nico. (*Disponible cuando la funci�n es compatible con el juego. **Comparado con el controlador inal�mbrico DUALSHOCK 4. �Se necesita Internet y cuenta para PlayStation Network.)',3,1),
	 ('Gamepad Sony DualSense White','1639949849450.jpg','2021-12-19 21:37:29',NULL,NULL,11999,'Enciende tus noches de juego en tu consola PS5 con el mando inal�mbrico DualSense Midnight Black. Parte de una nueva gama de colores tem�ticos de galaxia, este elegante dise�o se inspira en c�mo vemos las maravillas del espacio a trav�s del cielo nocturno, con tonos sutiles de detalles en negro y gris claro. Descubre una experiencia de juego m�s profunda y altamente envolvente** que da vida a la acci�n en las palmas de tus manos. El controlador inal�mbrico DualSense ofrece una respuesta t�ctil envolvente*, disparadores adaptativos din�micos* y un micr�fono integrado, todo integrado en un c�modo dise�o ic�nico. (*Disponible cuando la funci�n es compatible con el juego. **Comparado con el controlador inal�mbrico DUALSHOCK 4. �Se necesita Internet y cuenta para PlayStation Network.)',3,1),
	 ('Xbox Core Controller Robot White','1639949917713.jpg','2021-12-19 21:38:37',NULL,NULL,12999,'Experimenta el dise�o modernizado del control inal�mbrico Xbox en color blanco robot, con superficies moldeadas y una geometr�a refinada para mayor comodidad durante el juego, con un rendimiento de la bater�a de hasta 40 horas. No pierdas de vista el objetivo con la almohadilla h�brida D, el agarre texturizado de los gatillos y la carcasa trasera. Captura y comparte contenido sin problemas como capturas de pantalla, grabaciones y mucho m�s con el bot�n compartir. Conectar a trav�s del puerto USB-C y enchufar directamente a la consola o PC. Se incluye soporte para pilas AA en la parte trasera. Conecta cualquier auricular compatible con el enchufe de audio de 3.5 mil�metros. Utiliza la aplicaci�n de accesorios de Xbox para asignar botones y crear perfiles de control personalizados para tus juegos favoritos. Forme pareja r�pidamente, juegue y cambie de dispositivos como Xbox Series X|S, Xbox One, PC Windows 10 y Android. Apoyo iOS en el futuro.',3,3);
INSERT INTO stationgame.products (name,image,creation_date,modified_date,deletion_date,price,description,category_id,brand_id) VALUES
	 ('Xbox Core Controller Shock Blue ','1639949947951.jpg','2021-12-19 21:39:07',NULL,NULL,12999,'Experimenta el dise�o modernizado del control inal�mbrico Xbox en color blanco robot, con superficies moldeadas y una geometr�a refinada para mayor comodidad durante el juego, con un rendimiento de la bater�a de hasta 40 horas. No pierdas de vista el objetivo con la almohadilla h�brida D, el agarre texturizado de los gatillos y la carcasa trasera. Captura y comparte contenido sin problemas como capturas de pantalla, grabaciones y mucho m�s con el bot�n compartir. Conectar a trav�s del puerto USB-C y enchufar directamente a la consola o PC. Se incluye soporte para pilas AA en la parte trasera. Conecta cualquier auricular compatible con el enchufe de audio de 3.5 mil�metros. Utiliza la aplicaci�n de accesorios de Xbox para asignar botones y crear perfiles de control personalizados para tus juegos favoritos. Forme pareja r�pidamente, juegue y cambie de dispositivos como Xbox Series X|S, Xbox One, PC Windows 10 y Android. Apoyo iOS en el futuro.',3,3),
	 ('Switch Pro Controller','1639950079801.jpg','2021-12-19 21:41:19',NULL,NULL,14999,'Adquiere el nuevo control Nintendo Switch Pro para explorar nuevas alternativas de juegos en tu consola Nintendo Switch

Eleva tu experiencia al maximo con las caracteristicas que posee este control, como control por movimiento, vibracion ultra realista y un espacio exclusivo para colocar tu amiibo y utilizarlo durante tus sesiones de juego.

No te demores mas y adquiri tu control Nintendo Switch Pro.',3,2);

insert into products (name, image, creation_date, modified_date, deletion_date, price, description, category_id, brand_id) values ('sapien in', 'default.jpg', '2021-05-31 05:39:22', '2021-06-11 09:39:05', '2021-10-12 15:19:51', 72113.1, 'morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor', 1, 2);
insert into products (name, image, creation_date, modified_date, deletion_date, price, description, category_id, brand_id) values ('amet', 'default.jpg', '2021-01-12 17:54:38', '2020-12-08 06:21:26', '2021-06-10 16:30:13', 182570.28, 'eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu', 3, 2);
insert into products (name, image, creation_date, modified_date, deletion_date, price, description, category_id, brand_id) values ('aenean lectus', 'default.jpg', '2021-08-14 01:10:57', '2021-03-11 17:49:43', '2021-05-12 07:24:20', 50701.54, 'ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien', 3, 3);
insert into products (name, image, creation_date, modified_date, deletion_date, price, description, category_id, brand_id) values ('platea dictumst', 'default.jpg', '2021-07-16 18:21:35', '2021-02-24 13:40:21', '2021-09-27 22:49:46', 88480.8, 'natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque', 2, 1);
insert into products (name, image, creation_date, modified_date, deletion_date, price, description, category_id, brand_id) values ('aliquam', 'default.jpg', '2021-04-25 01:31:11', '2021-05-04 09:40:36', '2021-10-14 23:38:26', 77381.37, 'aenean sit amet justo morbi ut odio cras mi pede malesuada in', 1, 2);
insert into products (name, image, creation_date, modified_date, deletion_date, price, description, category_id, brand_id) values ('diam cras', 'default.jpg', '2021-04-18 18:01:26', '2021-05-04 06:10:19', '2021-02-22 02:58:02', 88477.95, 'dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate', 1, 2);
insert into products (name, image, creation_date, modified_date, deletion_date, price, description, category_id, brand_id) values ('felis', 'default.jpg', '2021-08-04 04:54:10', '2021-11-07 22:26:29', '2021-11-01 00:32:24', 199894.18, 'nec condimentum neque sapien placerat ante nulla justo aliquam quis', 1, 2);
insert into products (name, image, creation_date, modified_date, deletion_date, price, description, category_id, brand_id) values ('ipsum', 'default.jpg', '2020-12-10 09:29:06', '2021-10-02 00:24:35', '2021-09-18 20:16:54', 122484.16, 'volutpat quam pede lobortis ligula sit amet eleifend pede libero', 1, 2);
insert into products (name, image, creation_date, modified_date, deletion_date, price, description, category_id, brand_id) values ('vitae', 'default.jpg', '2021-09-12 23:14:37', '2021-04-17 18:49:38', '2020-12-25 14:49:40', 9151.58, 'sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh', 3, 1);
insert into products (name, image, creation_date, modified_date, deletion_date, price, description, category_id, brand_id) values ('interdum in', 'default.jpg', '2021-10-08 03:01:52', '2021-12-03 17:22:21', '2021-02-10 01:56:15', 50161.41, 'eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in', 3, 1);
insert into products (name, image, creation_date, modified_date, deletion_date, price, description, category_id, brand_id) values ('dapibus', 'default.jpg', '2021-09-15 09:13:34', '2021-07-08 08:52:46', '2021-05-17 13:27:04', 81757.14, 'pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas', 1, 2);
insert into products (name, image, creation_date, modified_date, deletion_date, price, description, category_id, brand_id) values ('luctus et', 'default.jpg', '2021-06-06 23:07:45', '2021-10-14 03:50:51', '2021-08-03 20:40:09', 93512.51, 'curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec', 2, 1);
insert into products (name, image, creation_date, modified_date, deletion_date, price, description, category_id, brand_id) values ('quisque', 'default.jpg', '2021-05-23 23:24:54', '2021-01-13 05:03:24', '2021-03-24 06:08:35', 107181.54, 'vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum', 1, 3);
insert into products (name, image, creation_date, modified_date, deletion_date, price, description, category_id, brand_id) values ('quis augue', 'default.jpg', '2021-11-18 22:29:57', '2021-12-05 04:14:33', '2021-03-03 19:58:30', 94021.77, 'consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla', 1, 1);
insert into products (name, image, creation_date, modified_date, deletion_date, price, description, category_id, brand_id) values ('eget', 'default.jpg', '2021-09-23 15:06:04', '2021-05-22 05:52:44', '2020-12-16 12:56:06', 125818.62, 'in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius', 3, 2);
insert into products (name, image, creation_date, modified_date, deletion_date, price, description, category_id, brand_id) values ('laoreet', 'default.jpg', '2021-06-12 12:18:16', '2021-10-01 17:27:02', '2021-04-08 19:11:38', 45381.25, 'ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate', 2, 2);
insert into products (name, image, creation_date, modified_date, deletion_date, price, description, category_id, brand_id) values ('lectus suspendisse', 'default.jpg', '2021-07-18 18:38:21', '2021-03-30 13:08:57', '2021-01-15 06:17:30', 179550.48, 'nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue', 2, 3);
insert into products (name, image, creation_date, modified_date, deletion_date, price, description, category_id, brand_id) values ('posuere', 'default.jpg', '2021-03-03 23:48:12', '2021-05-29 14:48:24', '2021-03-11 23:07:59', 7991.65, 'felis fusce posuere felis sed lacus morbi sem mauris laoreet ut', 2, 1);
insert into products (name, image, creation_date, modified_date, deletion_date, price, description, category_id, brand_id) values ('convallis', 'default.jpg', '2021-04-01 13:05:44', '2021-05-15 09:03:53', '2020-12-22 09:39:10', 86230.55, 'libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in', 3, 2);
insert into products (name, image, creation_date, modified_date, deletion_date, price, description, category_id, brand_id) values ('volutpat', 'default.jpg', '2021-07-31 04:59:56', '2020-12-07 23:40:15', '2021-07-17 10:23:01', 176555.87, 'arcu libero rutrum ac lobortis vel dapibus at diam nam tristique', 2, 3);
insert into products (name, image, creation_date, modified_date, deletion_date, price, description, category_id, brand_id) values ('augue', 'default.jpg', '2021-06-10 19:19:46', '2021-01-08 06:27:03', '2021-02-12 06:46:16', 186548.63, 'porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci', 3, 3);
insert into products (name, image, creation_date, modified_date, deletion_date, price, description, category_id, brand_id) values ('a', 'default.jpg', '2021-09-26 20:06:36', '2021-03-06 09:25:38', '2021-09-29 02:28:35', 77936.36, 'dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede', 1, 1);
insert into products (name, image, creation_date, modified_date, deletion_date, price, description, category_id, brand_id) values ('justo sollicitudin', 'default.jpg', '2021-11-02 21:43:08', '2021-02-06 01:50:47', '2021-03-12 10:35:28', 130242.69, 'nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id', 3, 2);
insert into products (name, image, creation_date, modified_date, deletion_date, price, description, category_id, brand_id) values ('ultrices posuere', 'default.jpg', '2021-09-08 11:42:41', '2021-10-01 01:25:03', '2021-08-31 02:34:06', 22801.06, 'non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros', 3, 2);
insert into products (name, image, creation_date, modified_date, deletion_date, price, description, category_id, brand_id) values ('odio condimentum', 'default.jpg', '2021-01-11 10:49:15', '2021-06-08 06:01:00', '2021-05-27 10:04:10', 153040.0, 'integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis', 1, 3);
insert into products (name, image, creation_date, modified_date, deletion_date, price, description, category_id, brand_id) values ('suscipit', 'default.jpg', '2021-09-29 16:35:08', '2021-11-28 14:40:44', '2021-02-02 14:13:54', 36949.67, 'lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui', 2, 3);
insert into products (name, image, creation_date, modified_date, deletion_date, price, description, category_id, brand_id) values ('justo', 'default.jpg', '2021-10-26 21:41:40', '2021-11-08 12:03:19', '2021-01-11 06:10:18', 99672.78, 'etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus', 1, 1);
insert into products (name, image, creation_date, modified_date, deletion_date, price, description, category_id, brand_id) values ('donec', 'default.jpg', '2021-04-06 05:15:07', '2021-11-30 16:10:48', '2021-09-20 19:16:07', 9545.38, 'faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet', 3, 1);
insert into products (name, image, creation_date, modified_date, deletion_date, price, description, category_id, brand_id) values ('accumsan', 'default.jpg', '2021-03-16 03:08:28', '2021-03-15 00:08:04', '2021-08-18 21:01:18', 175893.52, 'nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper', 1, 2);
insert into products (name, image, creation_date, modified_date, deletion_date, price, description, category_id, brand_id) values ('in', 'default.jpg', '2021-01-02 14:50:35', '2021-11-27 01:12:44', '2021-08-27 23:38:50', 50978.38, 'vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti', 1, 3);
insert into products (name, image, creation_date, modified_date, deletion_date, price, description, category_id, brand_id) values ('turpis', 'default.jpg', '2021-03-10 13:42:02', '2020-12-28 15:07:27', '2021-09-27 07:35:18', 184318.66, 'ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in', 2, 1);
insert into products (name, image, creation_date, modified_date, deletion_date, price, description, category_id, brand_id) values ('ante nulla', 'default.jpg', '2021-01-08 07:34:05', '2021-05-23 17:40:08', '2020-12-21 05:31:40', 64928.29, 'tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien', 1, 2);
insert into products (name, image, creation_date, modified_date, deletion_date, price, description, category_id, brand_id) values ('sapien cum', 'default.jpg', '2021-04-09 12:36:58', '2021-06-19 07:49:24', '2021-08-30 10:47:20', 4993.02, 'elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac', 3, 1);
insert into products (name, image, creation_date, modified_date, deletion_date, price, description, category_id, brand_id) values ('mauris', 'default.jpg', '2021-04-03 05:12:43', '2021-10-25 20:29:59', '2021-10-19 21:20:34', 187548.84, 'penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis', 3, 3);